// Access to the `@midnight-ntwrk/compact-runtime` instance used by THE
// GENERATED CONTRACT.
//
// ── The problem this guards against ─────────────────────────────────────
// If two physical copies of compact-runtime (and its wasm
// `onchain-runtime-v3`) end up installed — e.g. one under
// `node_modules/@midnight-ntwrk/compact-runtime` (seen by app/) and another
// under `contracts/node_modules/...` (seen by the generated contract) — they
// are two distinct instances of the same wasm module, so the `instanceof`
// checks the runtime uses to validate its arguments fail when crossing them:
//
//   CompactError: 'contractState' parameter Array(5) [...] has unexpected type
//       at coerceToChargedState (compact-runtime/dist/circuit-context.js:33)
//
// The object IS a ChargedState — but from the OTHER copy, so it is not an
// `instanceof` of the class the validator knows.
//
// ── The real fix (NOT this module's job) ────────────────────────────────
// Delete the nested `contracts/node_modules/` (a stale nested install; both
// copies are the SAME version, so deduplication makes everything resolve to
// the root) and reinstall from the root. And it genuinely matters:
// `@midnight-ntwrk/midnight-js-contracts` (block B3) creates contexts with
// ITS own copy of the runtime — the root one — so this module's trick does
// not save it. While two copies exist, B3 hits the same CompactError as soon
// as it tries to deploy or call a circuit.
//
// ── What this module does ───────────────────────────────────────────────
// Resolves the `@midnight-ntwrk/compact-runtime` specifier THE WAY THE
// CONTRACT RESOLVES IT (from the generated module's URL) and imports that
// same instance. Node's ESM module cache is indexed by resolved URL, so we
// get exactly the object the contract already has loaded and the
// `instanceof` checks hold.
//
// With a deduplicated install both paths coincide and this module returns
// the root copy without changing a line: it stays correct after the fix.

import { createRequire } from 'node:module';
import { pathToFileURL } from 'node:url';

import type * as CompactRuntime from '@midnight-ntwrk/compact-runtime';

/** The module generated by `compact compile`. */
export const CONTRACT_URL = new URL(
  '../../../contracts/output/contract/index.js',
  import.meta.url,
);

/** Runtime path as the contract resolves it. */
export const contractRuntimePath: string = createRequire(CONTRACT_URL).resolve(
  '@midnight-ntwrk/compact-runtime',
);

/** Runtime path as `app/` resolves it. */
export const appRuntimePath: string = createRequire(import.meta.url).resolve(
  '@midnight-ntwrk/compact-runtime',
);

/**
 * true when there is a SINGLE installed copy, which is how it must be.
 * If false, B3 will hit the CompactError described above.
 */
export const runtimeUnified: boolean = contractRuntimePath === appRuntimePath;

/**
 * The compact-runtime instance that shares a realm with the contract.
 * The types come from the package installed at the root: same exact version
 * (0.16.0), so the shape is identical; the only thing that changes is the
 * runtime identity of the classes.
 */
export const runtime = (await import(
  pathToFileURL(contractRuntimePath).href
)) as typeof CompactRuntime;
