// B2.3 — The contract's 6 witnesses + the private state feeding them.
//
// Typed against `contracts/output/contract/index.d.ts`, the .d.ts generated
// by `compact compile`. Nothing about this shape is invented: if the contract
// changes and is recompiled, `tsc -p app` breaks here.
//
// The relative path to the generated contract has the SAME depth from
// `app/src/witnesses/` as from `app/dist/witnesses/`, so it works both for
// the typecheck and at runtime after `tsc -p app`.

import type { Ledger, Witnesses } from '../../../contracts/output/contract/index.js';
import { pureCircuits } from '../../../contracts/output/contract/index.js';

import { MERKLE_DEPTH } from '@phantomtrace/shared/crypto';

import { type Hex32, toHex, randomBytes32, asBytes32 } from './hex.js';
import type { ReportRecord, WhistleblowerSecrets } from './secrets.js';

export { pureCircuits };
export type { Ledger, Witnesses };

// ─────────────────────────────────────────────────────────────────────────
// Errors
// ─────────────────────────────────────────────────────────────────────────

/**
 * The only error `credentialPath` can raise.
 *
 * SECURITY (docs/03 §3.4, rule 4 of H-5): fail CLOSED and with a SINGLE
 * message. "You are not an employee of this org", "you have a credential but
 * it was not issued yet" and "there is no credential loaded" are NOT
 * distinguished: the three situations exit through the same place, with the
 * same text, having done the same work (see `credentialBytes`). A more
 * specific message would be an organization-membership oracle.
 */
export class CredentialNotIssuedError extends Error {
  constructor() {
    super('credential not issued for this org');
    this.name = 'CredentialNotIssuedError';
  }
}

/**
 * The app called a circuit that needs a report's secrets without staging it
 * first. It is an app bug, not a ledger condition: it happens 100% locally,
 * before generating a proof and without submitting a tx.
 */
export class ReportNotStagedError extends Error {
  constructor(circuit: string) {
    super(
      `no active report in the private state (needed by "${circuit}"). ` +
        'Since witnesses take no arguments, the app must stage the report ' +
        'with stageNewReport()/stageStoredReport() BEFORE calling the circuit.',
    );
    this.name = 'ReportNotStagedError';
  }
}

export class ReportMismatchError extends Error {
  constructor(expected: Hex32, got: Hex32) {
    super(
      `the stored secrets do not reconstruct that report: ` +
        `expected ${expected}, got ${got}`,
    );
    this.name = 'ReportMismatchError';
  }
}

// ─────────────────────────────────────────────────────────────────────────
// Private state
// ─────────────────────────────────────────────────────────────────────────

/**
 * The private state's report "in focus".
 *
 * Exists because Compact witnesses TAKE NO ARGUMENTS: `personalSecret()` and
 * `evidenceHash()` only see `context.privateState`. Since the security review
 * mandates a distinct secret PER REPORT (H-3, docs/03 §3.4), the only channel
 * to tell the witness *which* of all the secrets to use is leaving the right
 * one staged here before invoking the circuit.
 */
export interface StagedReport {
  /** Fresh secret of THIS report. Never shared with another one. */
  readonly reportSecret: Uint8Array;
  /** sha-256 of the evidence file, computed locally (see evidence.ts). */
  readonly evidenceHash: Uint8Array;
  /** `reportIdOf(evidenceHash, reportSecret)`, precomputed. */
  readonly reportId: Uint8Array;
}

/**
 * The contract's private state (the `PS` of `Witnesses<PS>`).
 *
 * Nothing here ever leaves the machine: it goes neither into the tx, nor to
 * the indexer, nor to the proof server except as input to the local proof.
 */
export interface TestigoPrivateState {
  readonly version: 2;
  /** Credential secret, generated by the client. null if there is none. */
  readonly credentialSecret: Uint8Array | null;
  /**
   * Org of the credential. It must be THE SAME `orgId` passed to
   * `report(orgId, period)`: the circuit rebuilds the leaf from its public
   * argument and the witness looks it up with this value. If they differ,
   * the in-circuit `checkRoot` fails — closed, but with a confusing error.
   */
  readonly orgId: Uint8Array | null;
  /** Report staged for the next `report` / `revealAuthorship`. */
  readonly activeReport: StagedReport | null;
  /**
   * The issuing organization's secret, whose `anchorOf` is the anchor
   * published by `registerOrganization`. Only the ISSUER holds this; a
   * whistleblower's state has it null. `issueCredential` asserts against it.
   */
  readonly issuerSecret: Uint8Array | null;
  /**
   * The nonce the prosecutor chose for the pending `revealAuthorship`.
   *
   * Same reason as `activeReport`: witnesses take no arguments, so the only
   * channel to tell `prosecutorNonce()` which nonce to use is staging it here
   * first. It arrives from the prosecutor off-chain and is not a secret of
   * ours — but it must not reach the transcript, so it travels as a witness.
   */
  readonly activeNonce: Uint8Array | null;
}

export function emptyPrivateState(): TestigoPrivateState {
  return {
    version: 2,
    credentialSecret: null,
    orgId: null,
    activeReport: null,
    issuerSecret: null,
    activeNonce: null,
  };
}

/** Loads the credential from the local store (`secrets/denunciante.json`). */
export function privateStateFromSecrets(
  secrets: WhistleblowerSecrets,
): TestigoPrivateState {
  return {
    version: 2,
    credentialSecret: asBytes32(secrets.credentialSecret, 'credentialSecret'),
    orgId: asBytes32(secrets.orgId, 'orgId'),
    activeReport: null,
    issuerSecret: null,
    activeNonce: null,
  };
}

export function withCredential(
  ps: TestigoPrivateState,
  credentialSecret: Uint8Array | Hex32,
  orgId: Uint8Array | Hex32,
): TestigoPrivateState {
  return {
    ...ps,
    credentialSecret: asBytes32(credentialSecret, 'credentialSecret'),
    orgId: asBytes32(orgId, 'orgId'),
  };
}

/**
 * Loads the ISSUER's secret. Only an organization running `issueCredential`
 * needs this; a whistleblower's state leaves it null.
 */
export function withIssuerSecret(
  ps: TestigoPrivateState,
  issuerSecret: Uint8Array | Hex32,
): TestigoPrivateState {
  return { ...ps, issuerSecret: asBytes32(issuerSecret, 'issuerSecret') };
}

/**
 * Stages the nonce the prosecutor sent, for the next `revealAuthorship` /
 * `proveAuthorship`. See `TestigoPrivateState.activeNonce`.
 */
export function stageNonce(
  ps: TestigoPrivateState,
  prosecutorNonce: Uint8Array | Hex32,
): TestigoPrivateState {
  return { ...ps, activeNonce: asBytes32(prosecutorNonce, 'prosecutorNonce') };
}

/** The org's published anchor for a given issuer secret. */
export function issuerAnchor(issuerSecret: Uint8Array | Hex32): Uint8Array {
  return pureCircuits.anchorOf(asBytes32(issuerSecret, 'issuerSecret'));
}

/**
 * The orgId that belongs to a given issuer secret (H-2).
 *
 * Since the audit fix an orgId is not chosen, it is derived:
 * `registerOrganization` asserts `orgIdOf(issuerSecret()) == orgId`, so an id
 * nobody can derive is an id nobody can squat. Callers must build the orgId
 * with this rather than picking one.
 */
export function organizationId(issuerSecret: Uint8Array | Hex32): Uint8Array {
  return pureCircuits.orgIdOf(asBytes32(issuerSecret, 'issuerSecret'));
}

export function hasCredential(ps: TestigoPrivateState): boolean {
  return ps.credentialSecret !== null && ps.orgId !== null;
}

/**
 * Commitment handed to the credential issuer.
 *
 * SECURITY (H-4): this — and not `credentialSecret` — is the only thing the
 * organization receives. With the secret it could recompute
 * `nullifierOf(credSecret, period)` for any employee and learn who
 * reported in each period.
 */
export function credentialCommitment(ps: TestigoPrivateState): Uint8Array {
  if (ps.credentialSecret === null) throw new CredentialNotIssuedError();
  return pureCircuits.credCommitmentOf(ps.credentialSecret);
}

/**
 * This credential's leaf in the global tree:
 * `leafOf(orgId, credCommitmentOf(credSecret))` — two hashes, same as inside
 * the `report` circuit.
 */
export function credentialLeaf(ps: TestigoPrivateState): Uint8Array {
  if (ps.credentialSecret === null || ps.orgId === null) throw new CredentialNotIssuedError();
  return pureCircuits.leafOf(ps.orgId, pureCircuits.credCommitmentOf(ps.credentialSecret));
}

// ── Staging of the active report ────────────────────────────────────────

/** `reportIdOf(evidenceHash, reportSecret)` from a record. */
export function reportIdOfRecord(record: {
  reportSecret: Uint8Array | Hex32;
  evidenceHash: Uint8Array | Hex32;
}): Uint8Array {
  return pureCircuits.reportIdOf(
    asBytes32(record.evidenceHash, 'evidenceHash'),
    asBytes32(record.reportSecret, 'reportSecret'),
  );
}

/**
 * Stages a NEW report with a freshly generated `reportSecret`.
 *
 * The secret comes from `crypto.randomBytes(32)` and is never reused: it is
 * the H-3 mitigation. It also returns the `reportId` and the secret in the
 * clear so B3 can persist them with `addReport()` — if they are lost, that
 * report has no way to reveal its authorship, ever.
 */
export function stageNewReport(
  ps: TestigoPrivateState,
  evidenceHash: Uint8Array | Hex32,
): { state: TestigoPrivateState; report: StagedReport } {
  const ev = asBytes32(evidenceHash, 'evidenceHash');
  const reportSecret = randomBytes32();
  const report: StagedReport = {
    reportSecret,
    evidenceHash: ev,
    reportId: pureCircuits.reportIdOf(ev, reportSecret),
  };
  return { state: { ...ps, activeReport: report }, report };
}

/**
 * Stages an ALREADY submitted report, read from the local store, for
 * `revealAuthorship`.
 *
 * With `expectedReportId` it locally verifies that the stored secrets
 * reconstruct that id. It is the same condition the circuit checks in its C1
 * ("not the author"), but it costs a hash instead of a full proof
 * generation: it saves burning ~30 s of proving on an inconsistent store.
 * It does NOT replace the circuit's assert, which is the one that counts.
 */
export function stageStoredReport(
  ps: TestigoPrivateState,
  record: ReportRecord | { reportSecret: Uint8Array | Hex32; evidenceHash: Uint8Array | Hex32 },
  expectedReportId?: Uint8Array | Hex32,
): TestigoPrivateState {
  const reportId = reportIdOfRecord(record);
  if (expectedReportId !== undefined) {
    const expected = toHex(asBytes32(expectedReportId, 'reportId'));
    if (toHex(reportId) !== expected) {
      throw new ReportMismatchError(expected, toHex(reportId));
    }
  }
  return {
    ...ps,
    activeReport: {
      reportSecret: asBytes32(record.reportSecret, 'reportSecret'),
      evidenceHash: asBytes32(record.evidenceHash, 'evidenceHash'),
      reportId,
    },
  };
}

/**
 * Takes the report out of focus. Best called as soon as the tx confirms: it
 * leaves the private state without a "ready to use" secret, so a later call
 * cannot sign with the wrong secret by mistake.
 */
export function clearActiveReport(ps: TestigoPrivateState): TestigoPrivateState {
  return { ...ps, activeReport: null };
}

// ─────────────────────────────────────────────────────────────────────────
// The witnesses
// ─────────────────────────────────────────────────────────────────────────

/**
 * Path length required by `HistoricMerkleTree<16, Bytes<32>>`.
 *
 * Imported, not repeated: this used to be a second literal `8` sitting a
 * workspace away from `MERKLE_DEPTH`, and a witness that hands the circuit a
 * path of the wrong length is rejected with an error that points nowhere near
 * the mismatch.
 */
const TREE_DEPTH = MERKLE_DEPTH;

/**
 * Bytes used to build the leaf to look up.
 *
 * If NO credential is loaded it returns random DECOYS instead of throwing.
 * It looks counterintuitive, and it is deliberate: it makes "I have no
 * credential", "I have a credential from another org" and "I have the right
 * credential but it was not issued yet" walk exactly the same path — the two
 * hashes, the same tree lookup — and exit through the same `throw`. Without
 * the decoy, the "no credential" case would cut short and be distinguishable
 * by timing, which is exactly what rule 4 of H-5 forbids.
 *
 * A 32-random-byte decoy is not in the tree with overwhelming probability,
 * so the outcome is always the same: closed failure.
 */
function credentialBytes(ps: TestigoPrivateState): {
  credentialSecret: Uint8Array;
  orgId: Uint8Array;
} {
  return {
    credentialSecret: ps.credentialSecret ?? randomBytes32(),
    orgId: ps.orgId ?? randomBytes32(),
  };
}

/**
 * Builds the witnesses object required by `new Contract(witnesses)`.
 *
 * The 6 are pure functions of the `WitnessContext`: they read the private
 * state and, in the path's case, the FRESH ledger. They keep no state of
 * their own between calls — any cache here would be a security bug (see
 * `credentialPath`).
 */
export function createWitnesses(): Witnesses<TestigoPrivateState> {
  return {
    /**
     * Credential secret (Option A). Feeds the anti-spam nullifier:
     * `nullifierOf(credSecret, period)`.
     */
    credentialSecret({ privateState }) {
      return [privateState, credentialBytes(privateState).credentialSecret];
    },

    /**
     * Merkle path siblings towards this credential's leaf.
     *
     * ⚠️ SECURITY PROPERTY, NOT CONVENIENCE (H-5, docs/03 §3.4):
     * `findPathForLeaf` is called in here, at proof time, against the ledger
     * state the runtime projects into `context.ledger` — the freshest the
     * machine knows. The path is NOT cached, NOT persisted in the private
     * state and NOT derived from the state at credential-issuance time.
     *
     * The reason: the root that `checkRoot` reveals in the public transcript
     * acts as a tree synchronization counter. An old path reveals an old
     * root, and the set of credentials existing when that root was current
     * is smaller than today's — in the limit, the root immediately after MY
     * credential's issuance points at my own index and identifies me
     * uniquely. Always recomputing makes every whistleblower reveal the
     * newest root and share the largest anonymity set available.
     * (Rule 3 of H-5, complementary: freeze `issueCredential` during the
     * demo, so the tree does not move and the leak is zero.)
     *
     * `contracts/test/sec-audit.mjs` block E keeps this reproduced: 4
     * insertions -> 4 distinct roots.
     */
    credentialPath({ privateState, ledger }) {
      const { credentialSecret, orgId } = credentialBytes(privateState);
      const leaf = pureCircuits.leafOf(orgId, pureCircuits.credCommitmentOf(credentialSecret));

      // Against the fresh ledger. Never against a stored copy.
      const path = ledger.credentials.findPathForLeaf(leaf);

      // Closed failure, single message: see CredentialNotIssuedError.
      if (path === undefined) throw new CredentialNotIssuedError();
      if (path.path.length !== TREE_DEPTH) throw new CredentialNotIssuedError();

      // The witness contributes ONLY the siblings. The leaf is rebuilt by
      // the circuit from its public `orgId`, so it cannot lie about which
      // organization the credential being proven belongs to.
      return [privateState, path.path];
    },

    /**
     * The secret that seals the report and later proves authorship.
     *
     * The witness is called `personalSecret` after its name in the
     * `.compact`, but since the review it is NOT a global personal secret:
     * it is the `reportSecret` of the STAGED report. A global secret allowed
     * a single reveal to retroactively de-anonymize all of the author's past
     * reports (H-3).
     */
    personalSecret({ privateState }) {
      if (privateState.activeReport === null) {
        throw new ReportNotStagedError('personalSecret');
      }
      return [privateState, privateState.activeReport.reportSecret];
    },

    /**
     * Hash of the evidence file. The file never leaves the machine (see
     * evidence.ts); by the time it gets here it is already 32 bytes.
     */
    evidenceHash({ privateState }) {
      if (privateState.activeReport === null) {
        throw new ReportNotStagedError('evidenceHash');
      }
      return [privateState, privateState.activeReport.evidenceHash];
    },

    /**
     * The organization's issuer secret. `issueCredential` asserts that its
     * `anchorOf` equals the anchor the org published, which is what keeps the
     * credential tree — a finite, unrecoverable resource — from being filled
     * by anyone who feels like it.
     *
     * Decoy on absence, same reasoning as `credentialBytes`: a caller with no
     * issuer secret must fail inside the circuit like any wrong secret does,
     * not short-circuit here into a distinguishable error.
     */
    issuerSecret({ privateState }) {
      return [privateState, privateState.issuerSecret ?? randomBytes32()];
    },

    /**
     * The nonce this reveal is addressed to. Staged with `stageNonce()` from
     * whatever the prosecutor sent over.
     *
     * It is a witness rather than a public circuit argument on purpose: a
     * public nonce would land in the transaction transcript, and anyone who
     * scraped the pair (reportId, nonce) could recompute the receipt and pass
     * themselves off as its addressee.
     */
    prosecutorNonce({ privateState }) {
      if (privateState.activeNonce === null) {
        throw new ReportNotStagedError('prosecutorNonce');
      }
      return [privateState, privateState.activeNonce];
    },
  };
}

/** Ready-made instance for `new Contract(witnesses)`. */
export const witnesses: Witnesses<TestigoPrivateState> = createWitnesses();

// ─────────────────────────────────────────────────────────────────────────
// Private state serialization
// ─────────────────────────────────────────────────────────────────────────
//
// ⚠️ If B1/B3 use `@midnight-ntwrk/midnight-js-level-private-state-provider`,
// this state gets written IN THE CLEAR to a LevelDB on disk. That directory
// must fall under `secrets/` (already gitignored) or be explicitly ignored:
// it is a second copy of the same secrets that `secrets/denunciante.json`
// protects with 0600.

export interface SerializedPrivateState {
  readonly version: 2;
  readonly credentialSecret: Hex32 | null;
  readonly orgId: Hex32 | null;
  readonly activeReport: {
    readonly reportSecret: Hex32;
    readonly evidenceHash: Hex32;
    readonly reportId: Hex32;
  } | null;
  /** Optional so a state written before contract v2 still loads. */
  readonly issuerSecret?: Hex32 | null;
  /** Optional for the same reason; transient anyway. */
  readonly activeNonce?: Hex32 | null;
}

export function privateStateToJson(ps: TestigoPrivateState): SerializedPrivateState {
  return {
    version: 2,
    credentialSecret: ps.credentialSecret === null ? null : toHex(ps.credentialSecret),
    orgId: ps.orgId === null ? null : toHex(ps.orgId),
    activeReport:
      ps.activeReport === null
        ? null
        : {
            reportSecret: toHex(ps.activeReport.reportSecret),
            evidenceHash: toHex(ps.activeReport.evidenceHash),
            reportId: toHex(ps.activeReport.reportId),
          },
    issuerSecret: ps.issuerSecret === null ? null : toHex(ps.issuerSecret),
    activeNonce: ps.activeNonce === null ? null : toHex(ps.activeNonce),
  };
}

export function privateStateFromJson(
  raw: SerializedPrivateState,
): TestigoPrivateState {
  if (raw.version !== 2) {
    throw new TypeError(`private state version ${String(raw.version)}, expected 2`);
  }
  return {
    version: 2,
    credentialSecret:
      raw.credentialSecret === null
        ? null
        : asBytes32(raw.credentialSecret, 'credentialSecret'),
    orgId: raw.orgId === null ? null : asBytes32(raw.orgId, 'orgId'),
    activeReport:
      raw.activeReport === null
        ? null
        : {
            reportSecret: asBytes32(raw.activeReport.reportSecret, 'reportSecret'),
            evidenceHash: asBytes32(raw.activeReport.evidenceHash, 'evidenceHash'),
            reportId: asBytes32(raw.activeReport.reportId, 'reportId'),
          },
    issuerSecret:
      raw.issuerSecret === null || raw.issuerSecret === undefined
        ? null
        : asBytes32(raw.issuerSecret, 'issuerSecret'),
    activeNonce:
      raw.activeNonce === null || raw.activeNonce === undefined
        ? null
        : asBytes32(raw.activeNonce, 'prosecutorNonce'),
  };
}
