// B2.1 — Local store of the whistleblower's secrets.
//
// Format v2 (docs/03-plan-ejecucion.md §3.2):
//
//   { "version": 2,
//     "credentialSecret": "<hex64>",
//     "orgId": "<hex64>",
//     "leafIndex": 3 | null,
//     "reports": { "<reportId>": { "reportSecret": "<hex64>",
//                                  "evidenceHash": "<hex64>" } } }
//
// ── Why v2: one secret PER REPORT, not a global one ─────────────────────
// Finding H-3 of the security review (docs/03 §3.4, reproduced in the
// simulator) is that a single `personalSecret` reused across all reports
// turns any authorship reveal into a RETROACTIVE de-anonymization of the
// whole history: whoever receives the export learns the secret and can
// recompute `reportIdOf(evidenceHash, secret)` for any evidence they
// suspect, attributing all the author's past reports to them. With a fresh
// secret per report, the damage of one reveal is bounded to THAT report.
//
// That is why `reports` is a map: each `reportId` stores the pair
// (reportSecret, evidenceHash) that generated it, and that is all it takes
// to reveal that report's authorship months later.
//
// The file lives under `secrets/`, which is already in `.gitignore`, and is
// written with 0600 permissions (owner only).

import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

import { isSerializedPeriod, periodToJson, periodFromJson } from './epoch.js';
import {
  type Hex32,
  toHex,
  randomBytes32,
  asHex32,
  isHex32,
} from './hex.js';

// ── Types of the persisted format ───────────────────────────────────────

export const SECRETS_VERSION = 2 as const;

export interface ReportRecord {
  /** Fresh secret of THIS report. Never reused for another one. */
  readonly reportSecret: Hex32;
  /** sha-256 of the evidence file (the file never leaves the machine). */
  readonly evidenceHash: Hex32;
  /**
   * Epoch in which it was submitted, as a decimal string.
   *
   * `period` is `Uint<64>` in the contract -> `bigint` in TS, and `bigint`
   * does not survive `JSON.stringify` (throws TypeError). It is stored
   * serialized and recovered with `periodOfRecord`. It is optional because it
   * is NOT needed to reveal authorship — `revealAuthorship` only uses
   * (reportSecret, evidenceHash). It stays as diagnostic data: it lets you
   * explain an "already reported this period" without guessing.
   */
  readonly period?: string;
}

/** Epoch of a record as a bigint, or null if it was not stored. */
export function periodOfRecord(record: ReportRecord): bigint | null {
  return record.period === undefined ? null : periodFromJson(record.period);
}

export interface WhistleblowerSecrets {
  readonly version: typeof SECRETS_VERSION;
  /** Credential secret. Generated by the CLIENT; the issuer never sees it. */
  readonly credentialSecret: Hex32;
  /** Organization that issued the credential. */
  readonly orgId: Hex32;
  /** Index of the leaf in the on-chain tree; null until issued. */
  readonly leafIndex: number | null;
  /** reportId -> secrets of that report. */
  readonly reports: Readonly<Record<Hex32, ReportRecord>>;
}

export class CorruptSecretsError extends Error {
  constructor(detail: string, public readonly path: string) {
    super(`invalid secrets at ${path}: ${detail}`);
    this.name = 'CorruptSecretsError';
  }
}

export class SecretsNotFoundError extends Error {
  constructor(public readonly path: string) {
    super(`no secrets at ${path} — run \`issue-credential\` first`);
    this.name = 'SecretsNotFoundError';
  }
}

// ── File location ───────────────────────────────────────────────────────

const FILE_MODE = 0o600;
const DIR_MODE = 0o700;

/**
 * Repo root: the first ancestor with a `package.json` declaring `workspaces`.
 * Resolved from the module location and NOT from `process.cwd()`, because
 * `npm run <script> --workspace=app` runs with cwd in `app/` while
 * `node dist/scripts/x.js` from the root runs with cwd at the root: without
 * this, the two would write secrets in different places and the whistleblower
 * would lose access to their own reports.
 */
function repoRoot(): string {
  let dir = path.dirname(fileURLToPath(import.meta.url));
  for (let i = 0; i < 12; i++) {
    const pj = path.join(dir, 'package.json');
    if (fs.existsSync(pj)) {
      try {
        const json: unknown = JSON.parse(fs.readFileSync(pj, 'utf8'));
        if (
          typeof json === 'object' &&
          json !== null &&
          'workspaces' in json
        ) {
          return dir;
        }
      } catch {
        // Unreadable package.json: keep climbing.
      }
    }
    const parent = path.dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  return process.cwd();
}

/**
 * Path of the store. Override with `TESTIGO_SECRETS` (the selftests use it so
 * they never touch the whistleblower's real secrets).
 */
export function secretsPath(): string {
  const override = process.env['TESTIGO_SECRETS'];
  if (override !== undefined && override !== '') return path.resolve(override);
  return path.join(repoRoot(), 'secrets', 'denunciante.json');
}

function resolve(filePath?: string): string {
  return filePath === undefined ? secretsPath() : path.resolve(filePath);
}

// ── Validation ──────────────────────────────────────────────────────────

function requireHex32(value: unknown, field: string, filePath: string): Hex32 {
  if (!isHex32(value)) {
    throw new CorruptSecretsError(`field "${field}" is not a 64-char hex string`, filePath);
  }
  return value;
}

function validate(raw: unknown, filePath: string): WhistleblowerSecrets {
  if (typeof raw !== 'object' || raw === null || Array.isArray(raw)) {
    throw new CorruptSecretsError('the JSON is not an object', filePath);
  }
  const o = raw as Record<string, unknown>;

  if (o['version'] !== SECRETS_VERSION) {
    throw new CorruptSecretsError(
      `version ${String(o['version'])}, expected ${SECRETS_VERSION}. ` +
        'The v1 format had a global `personalSecret`, insecure per H-3 ' +
        '(docs/03 §3.4): it is not migrated automatically, re-issue instead.',
      filePath,
    );
  }

  const leafIndex = o['leafIndex'];
  if (
    leafIndex !== null &&
    !(typeof leafIndex === 'number' && Number.isInteger(leafIndex) && leafIndex >= 0)
  ) {
    throw new CorruptSecretsError('"leafIndex" is not an integer >= 0 nor null', filePath);
  }

  const rawReports = o['reports'];
  if (
    typeof rawReports !== 'object' ||
    rawReports === null ||
    Array.isArray(rawReports)
  ) {
    throw new CorruptSecretsError('"reports" is not an object', filePath);
  }

  const reports: Record<Hex32, ReportRecord> = {};
  for (const [id, value] of Object.entries(rawReports as Record<string, unknown>)) {
    requireHex32(id, `reports["${id}"] (the key)`, filePath);
    if (typeof value !== 'object' || value === null) {
      throw new CorruptSecretsError(`reports["${id}"] is not an object`, filePath);
    }
    const r = value as Record<string, unknown>;
    const period = r['period'];
    if (period !== undefined && !isSerializedPeriod(period)) {
      throw new CorruptSecretsError(
        `reports["${id}"].period is not a decimal integer string`,
        filePath,
      );
    }
    reports[id] = {
      reportSecret: requireHex32(r['reportSecret'], `reports["${id}"].reportSecret`, filePath),
      evidenceHash: requireHex32(r['evidenceHash'], `reports["${id}"].evidenceHash`, filePath),
      ...(period === undefined ? {} : { period }),
    };
  }

  return {
    version: SECRETS_VERSION,
    credentialSecret: requireHex32(o['credentialSecret'], 'credentialSecret', filePath),
    orgId: requireHex32(o['orgId'], 'orgId', filePath),
    leafIndex: leafIndex as number | null,
    reports,
  };
}

// ── Read / write ────────────────────────────────────────────────────────

export function secretsExist(filePath?: string): boolean {
  return fs.existsSync(resolve(filePath));
}

/** Returns null if the file does not exist. Throws if it exists but is broken. */
export function readSecrets(filePath?: string): WhistleblowerSecrets | null {
  const target = resolve(filePath);
  if (!fs.existsSync(target)) return null;

  // If someone loosened the permissions (e.g. by copying the file), they are
  // fixed here: a secrets file readable by group/others is useless.
  const mode = fs.statSync(target).mode & 0o777;
  if (mode !== FILE_MODE) {
    fs.chmodSync(target, FILE_MODE);
    console.warn(
      `[secrets] permissions ${mode.toString(8)} on ${target} — fixed to 600`,
    );
  }

  let raw: unknown;
  try {
    raw = JSON.parse(fs.readFileSync(target, 'utf8'));
  } catch (e) {
    throw new CorruptSecretsError(`unreadable JSON (${String(e)})`, target);
  }
  return validate(raw, target);
}

/** Same as `readSecrets` but throws if the file does not exist. */
export function requireSecrets(filePath?: string): WhistleblowerSecrets {
  const s = readSecrets(filePath);
  if (s === null) throw new SecretsNotFoundError(resolve(filePath));
  return s;
}

/**
 * Atomic write with 0600 permissions.
 *
 * Written to a temp file and renamed: if the process dies halfway, the old
 * file stays intact. Losing this file in the middle of a write means losing
 * access to the already-submitted reports — there is no backup. The temp file
 * is created already in 0600 mode and `rename` preserves the mode, so the
 * bytes never exist on disk with lax permissions.
 */
export function writeSecrets(secrets: WhistleblowerSecrets, filePath?: string): void {
  const target = resolve(filePath);
  const dir = path.dirname(target);
  fs.mkdirSync(dir, { recursive: true, mode: DIR_MODE });

  const tmp = path.join(dir, `.${path.basename(target)}.${process.pid}.tmp`);
  const json = `${JSON.stringify(secrets, null, 2)}\n`;
  fs.writeFileSync(tmp, json, { mode: FILE_MODE });
  try {
    fs.renameSync(tmp, target);
  } catch (e) {
    fs.rmSync(tmp, { force: true });
    throw e;
  }
  fs.chmodSync(target, FILE_MODE);
}

// ── High-level operations ───────────────────────────────────────────────

/**
 * Creates the store with a fresh `credentialSecret` and persists it.
 *
 * SECURITY (H-4, docs/03 §3.4): the secret is generated by THE CLIENT, here.
 * The credential issuer is sent only `credCommitmentOf(credentialSecret)`.
 * If the issuer generated the secret, it could recompute
 * `nullifierOf(credSecret, period)` for any employee and
 * de-anonymize who reported in each period.
 */
export function createSecrets(orgId: Uint8Array | Hex32, filePath?: string): WhistleblowerSecrets {
  const secrets: WhistleblowerSecrets = {
    version: SECRETS_VERSION,
    credentialSecret: toHex(randomBytes32()),
    orgId: asHex32(orgId, 'orgId'),
    leafIndex: null,
    reports: {},
  };
  writeSecrets(secrets, filePath);
  return secrets;
}

/** Reads the existing secrets or creates new ones for `orgId`. */
export function readOrCreateSecrets(
  orgId: Uint8Array | Hex32,
  filePath?: string,
): WhistleblowerSecrets {
  const existing = readSecrets(filePath);
  if (existing === null) return createSecrets(orgId, filePath);

  const expected = asHex32(orgId, 'orgId');
  if (existing.orgId !== expected) {
    throw new CorruptSecretsError(
      `the secrets belong to org ${existing.orgId}, ${expected} was requested. ` +
        'Use another path (TESTIGO_SECRETS) instead of overwriting the current credential.',
      resolve(filePath),
    );
  }
  return existing;
}

/** Stores the leaf index returned by `issueCredential`. */
export function setLeafIndex(leafIndex: number, filePath?: string): WhistleblowerSecrets {
  const current = requireSecrets(filePath);
  const next: WhistleblowerSecrets = { ...current, leafIndex };
  writeSecrets(next, filePath);
  return next;
}

/**
 * Fresh secret for ONE report. Called once per report; the result is never
 * reused (see the v2 note above).
 */
export function newReportSecret(): Uint8Array {
  return randomBytes32();
}

/**
 * Registers the secrets of a submitted report.
 *
 * Refuses to overwrite an existing `reportId` with different data:
 * overwriting would erase the only secret that allows revealing that
 * report's authorship, and it is unrecoverable. Re-registering the same
 * values is idempotent.
 */
export function addReport(
  reportId: Uint8Array | Hex32,
  record: {
    reportSecret: Uint8Array | Hex32;
    evidenceHash: Uint8Array | Hex32;
    period?: bigint;
  },
  filePath?: string,
): WhistleblowerSecrets {
  const current = requireSecrets(filePath);
  const id = asHex32(reportId, 'reportId');
  const newRecord: ReportRecord = {
    reportSecret: asHex32(record.reportSecret, 'reportSecret'),
    evidenceHash: asHex32(record.evidenceHash, 'evidenceHash'),
    ...(record.period === undefined ? {} : { period: periodToJson(record.period) }),
  };

  const previous = current.reports[id];
  if (previous !== undefined) {
    if (
      previous.reportSecret !== newRecord.reportSecret ||
      previous.evidenceHash !== newRecord.evidenceHash
    ) {
      throw new CorruptSecretsError(
        `report ${id} is already registered with different secrets — ` +
          'overwriting it would leave that report with no way to reveal authorship',
        resolve(filePath),
      );
    }
    return current;
  }

  const next: WhistleblowerSecrets = {
    ...current,
    reports: { ...current.reports, [id]: newRecord },
  };
  writeSecrets(next, filePath);
  return next;
}

/** Secrets of one report, or null if it is not in the store. */
export function getReport(
  reportId: Uint8Array | Hex32,
  filePath?: string,
): ReportRecord | null {
  const current = requireSecrets(filePath);
  return current.reports[asHex32(reportId, 'reportId')] ?? null;
}

/** Locally registered reportIds, in insertion order. */
export function listReports(filePath?: string): Hex32[] {
  return Object.keys(requireSecrets(filePath).reports);
}
